name: Feature Request
description: We love to hear about ways in which we can improve!
title: "[Feature]: "
labels: ["feature", "triage"]
assignees:
  - sethmbrown
  - quiquelores
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: nature-of-request
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      placeholder: The more detail, the better!
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like to see
      description: A clear and concise description of what you want to happen.
      placeholder: Let us know what you want!
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: What else might help?
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Give us all the info you want!
